/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SalesProofRouteImport } from './routes/sales-proof'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiPublicChatRouteImport } from './routes/api/public/chat'
import { Route as ApiPublicAuditRouteImport } from './routes/api/public/audit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesProofRoute = SalesProofRouteImport.update({
  id: '/sales-proof',
  path: '/sales-proof',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuditRoute = ApiPublicAuditRouteImport.update({
  id: '/api/public/audit',
  path: '/api/public/audit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sales-proof': typeof SalesProofRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/api/public/audit': typeof ApiPublicAuditRoute
  '/api/public/chat': typeof ApiPublicChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sales-proof': typeof SalesProofRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/api/public/audit': typeof ApiPublicAuditRoute
  '/api/public/chat': typeof ApiPublicChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sales-proof': typeof SalesProofRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/api/public/audit': typeof ApiPublicAuditRoute
  '/api/public/chat': typeof ApiPublicChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sales-proof'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/api/public/audit'
    | '/api/public/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sales-proof'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/api/public/audit'
    | '/api/public/chat'
  id:
    | '__root__'
    | '/'
    | '/sales-proof'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/api/public/audit'
    | '/api/public/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SalesProofRoute: typeof SalesProofRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ApiPublicAuditRoute: typeof ApiPublicAuditRoute
  ApiPublicChatRoute: typeof ApiPublicChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-proof': {
      id: '/sales-proof'
      path: '/sales-proof'
      fullPath: '/sales-proof'
      preLoaderRoute: typeof SalesProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/audit': {
      id: '/api/public/audit'
      path: '/api/public/audit'
      fullPath: '/api/public/audit'
      preLoaderRoute: typeof ApiPublicAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SalesProofRoute: SalesProofRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  ApiPublicAuditRoute: ApiPublicAuditRoute,
  ApiPublicChatRoute: ApiPublicChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
